### ISSUE TITLE
Better form progress handling

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/name-app#6]
Submitting a tx can take up to 5s with the default demo net config. Users will likely click a few times if there is no feedback. We should have the following feedback on buy and transfer (and optionally search which is much faster):

* When submitting the action, set the button to disabled and show some loading spinner
* Upon success, update the state (eg. name is free, buy it -> you own the name, transfer it)
* On error, show error above and enable button again with no loading icon
* For transfer, make the text entry box also disabled while we are waiting for response from submitting tx

For spinners, grab one you like. If you don't have a favorite, this seems like a nice gallery: https://github.danielcardoso.net/load-awesome/animations.html

Or browse https://github.com/yangshun/awesome-spinners

**Comment by Steve-Reid** [comment]
Currently, the search and transfer should disable when submitting. I can refactor the buy button to do the same and add a spinner.
Can you give me a transfer address that will work?

**Comment by ethanfrey** [comment]
You mean an address to send to?
I try to send to the contract address, which is valid. 

Or look up john or hello. I registered both.

Or send to yourself.... I think that is also legal
